# Server Port Configuration
server.port=${PORT:5001}

# MongoDB Atlas Connection Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://manrajtoorsingh_db_user:Manrajtoor22@cluster0.ezmbhek.mongodb.net/homespot?appName=Cluster0}

# Security & JWT Configuration
jwt.secret=${JWT_SECRET:supersecretkey123}
jwt.expirationMs=2592000000

# Jackson JSON formatting
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null

# Spring Logging
logging.level.org.springframework.web=INFO
logging.level.com.homespot=DEBUG
